# Jekyll configuration

gems: [jekyll-paginate]

name: Ezio Zhang
description: Embedded Software Developer , BSP and OS develop .

# Url is currently only used only for the RSS feed in feed.xml
url: ''
#http://localhost:4000

# For a project page here should be a project name. Otherwise (for user's/organizaion's page leave it empty)
baseurl: "/study-notes"
#'/jekyll-clean-dark'

share:
  facebook: true
  twitter: true
  gplus: true
  linkedin: true
  pinterest: true
  email: true

social:
  github: 'oska874' 
  stackoverflow: '1294322'
  linkedin: 'zhang-lei-1b41b669'
  rss: feed.xml

# Google Analytics key, leave blank to ignore
#google_analytics_key:
# Yandex metrika (https://metrica.yandex.com/) leave blank to ignore or put true to use
#yandex_metrica:


# Set this to your disqus shortname to enable comments. Note that the 'comments'
# setting below must also be true. Individual posts can override 'comments' to
# disable on a post-by-post basis
disqus: oska874githubiostudynotes
comments: true

permalink: /:year/:month/:title

# Enable for using pages, more details are here: http://jekyllrb.com/docs/pagination/
paginate: 3

#highlighter: rouge

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']

defaults:
  - 
    scope:
      path: ""
    values:
      layout: "post"

  - 
    scope:
      path: "sw/uboot"
    values:
      tags : "uboot"
      layout : "post"

  - 
    scope:
      path: sw/rtos"
    values:
      tags : "rtos"
      layout : "post"

  - 
    scope:
      path: "sw/aosp"
    values:
      tags : "android"
      layout : "post"

